### ISSUE TITLE
Hello, 请问您和你的日记这个应用有什么关联吗？

### ISSUE THREAD

**Issue by YunYouJun** [hxdnshx/YourDiaryAPI#1]
因为担心数据丢失，所以想要导出《你的日记》的内容。但是询问客服没有导出功能。
所以就想着自己写个导出功能的工具，通过抓包发现数据来自 `Ohshenghuo` 的网站，测试出了些 `api` ，但然后在想会不会重复劳动，又搜到了你的这个项目。
……所以想请问这之间有什么关联吗？

**Comment by hxdnshx** [comment]
您好，非常感谢关注到这个项目。抱歉由于个人原因之前没有完全完成Ohshenghuo api的提取。
目前我了解到的信息是（在2017年）：
1.Ohshenghuo与 你的日记 采用的是相同的用户名与密码。
2.Ohshenghuo中同样可以查看到在 你的日记 中书写的记录。
3.Ohshenghuo中写入的新的日志，在 你的日记 中可能无法对应查看。

**Comment by YunYouJun** [comment]
感谢您的回复，昨天前两条信息也有试验到，目前在测试相关的 api ，打算编写导出功能。不过现在 Ohshenghuo 中写入新的日志，在 `你的日记` 中也可对应查看。

**Comment by hxdnshx** [comment]
关于3. 之前测试，在同一天写入多条记录时， 你的日记端 可能会显示为 ta 的日期（或者不显示，记不清了），可能需要进一步测试。

**Comment by YunYouJun** [comment]
好的，感谢您提供的信息。 不过我只是打算写导出，所以应该不用担心到写入方面问题。:sunglasses:
